eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9094
spring:
  application:
    name: Employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/wipro_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true